### PR TITLE
[Task] External Pages Section

### PR DESCRIPTION
**Pull request by egiegarciano14**
## Related Links

- Task Link: https://www.notion.so/External-Pages-Section-ed15c5df78a04fc7af277fe2b324275b

## Description
- About page `http://localhost:3000/about-swipet`
- FAQ page `http://localhost:3000/faq`
- Privacy policy page `http://localhost:3000/privacy-policy`
- Terms & Conditions page `http://localhost:3000/terms-and-conditions`

## Notes
- ### I did not include the footer, once Joash footer task will be merged I will update the pr

## Screenshots
image
image
image
image
image

### CODE REVIEW

**Comment by ume45876139** [comment]
# Comment
## Chrome
<details>
<summary>Screenshot</summary>

スクリーンショット 2022-04-28 18 49 29

</details>

- [x] Logo should be redirect to home

# Testing data
test device: Chrome
test time: 0.25h

**Comment by ume45876139** [comment]
# Working
<details>
<summary>PC</summary>

スクリーンショット 2022-04-28 19 09 55

スクリーンショット 2022-04-28 19 10 17

スクリーンショット 2022-04-28 19 10 35

スクリーンショット 2022-04-28 19 11 10

</details>

<details>
<summary>Tablet</summary>

Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-04-28 at 19 11 35

Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-04-28 at 19 12 12

Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-04-28 at 19 12 45

Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-04-28 at 19 13 03

</details>

# Comment


<details>
<summary>Mobile</summary>

IMG_8013

IMG_8014

IMG_8015

https://user-images.githubusercontent.com/39412730/165731914-e1fc8053-ad99-4737-99a3-d9b219af4922.MP4

</details>

- [x] About Mobile, title text is overlapping

# Testing data
test device: Chrome, Safari (Mac)
test time: 0.25h

**Review by ume45876139 — APPROVED** [review]
# Working
<details>
<summary>PC</summary>

スクリーンショット 2022-04-28 19 09 55

スクリーンショット 2022-04-28 19 10 17

スクリーンショット 2022-04-28 19 10 35

スクリーンショット 2022-04-28 19 11 10

</details>

<details>
<summary>Tablet</summary>

Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-04-28 at 19 11 35

Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-04-28 at 19 12 12

Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-04-28 at 19 12 45

Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-04-28 at 19 13 03

</details>

<details>
<summary>Mobile</summary>


https://user-images.githubusercontent.com/39412730/165735621-8bcc7c36-ab8a-4fe1-a538-f03ebad12adb.MP4


https://user-images.githubusercontent.com/39412730/165735692-30011a58-dd8d-4850-82f6-44756b5673e0.MP4


https://user-images.githubusercontent.com/39412730/165735728-8ee1a794-bb65-4188-91f3-bff9778b9162.MP4


https://user-images.githubusercontent.com/39412730/165735740-03415d02-df7e-4f07-90ae-9ed214de0c33.MP4


</details>

- Logo is redirect to home
- No deformation
- Header is floating

# Testing data
test device: Chrome, Safari (Mac)
test time: 0.25h
total test time: 0.75h
comments:2
iteration: 2

**Comment by roseaugusto** [comment]
@egiegarciano14 
No need sub-folders
image

These can be combine in `constants.js`
image

**Review by ume45876139 — APPROVED** [review]
# Working

<details>
<summary>PC</summary>

https://user-images.githubusercontent.com/39412730/165893540-5f005727-e7db-4e06-9ebd-88bc0a2e4e77.mov

</details>

- Footer is working
    - About
    - FAQ page 
    - Privacy policy page
    - Terms & Conditions page
- Link is working

# Testing data
test device: Chrome, Safari (Mac)
test time: 0.1h
comment: 2
iteration: 2
total test time: 0.85

**Review by roseaugusto — APPROVED** [review]
Approved!

**Pull request merged**
