### PR TITLE
[Task] Feature Detail Pages

### PR DESCRIPTION
**Pull request by roseaugusto**
## Related Links

- Task Link: https://app.asana.com/0/1202252431396579/1202289494314480/f
- Figma Link: https://www.figma.com/file/Kyx9OK9MNRiUclwxsUe5BR/Rose-SwiPet?node-id=326%3A858
- Route Link: 
   - http://localhost:3000/feature/profile
   - http://localhost:3000/feature/match
   - http://localhost:3000/feature/chat
   - http://localhost:3000/feature/adopt

## Description

- [ ] Make wireframe for relevant contents
- [ ] Implementation

## Notes
Excluded Features
1. Small | Medium devices responsiveness
2. Dark theme
3. Demo Section (http://localhost:3000/feature/chat)
4. Fast forward counting Animation in Summary Section (http://localhost:3000/feature/match)
5. Update images for available pets section (http://localhost:3000/feature/adopt)
6. Translation of Japanese text

## Screenshots

N/A

### CODE REVIEW

**Comment by ume45876139** [comment]
# Comment
<details>
<summary>http://localhost:3000/feature/adopt</summary>

スクリーンショット 2022-06-02 11 09 43

</details>

- [ ] Is this text is need? This is not displayed at home directory. If need, should be lighter.

# Testing data
test device: Chrome, Safari (Mac)
test time: 0.5h

**Comment by roseaugusto** [comment]
> # Comment
> * [ ]  Is this text is need? This is not displayed at home directory. If need, should be lighter.

@ume45876139 Dark mode feature is not yet included in this pr 🙇‍♀️

**Comment by ume45876139** [comment]
# Working

<details>
<summary>Browser</summary>

https://user-images.githubusercontent.com/39412730/171590127-5072c36f-eb46-49d7-a7a8-dfd828793dde.mp4


</details>

# Comments

<details>
<summary>iPad</summary>

http://localhost:3000/feature/match

Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-06-02 at 17 26 02

</details>

<details>
<summary>iPhone</summary>

http://localhost:3000/feature/match

IMG_8225

http://localhost:3000/feature/chat

IMG_8226

</details>

- [ ] There is deformation at iPad and iPhone


# Testing data
test device: Chrome, Safari
test time: 0.5h

**Comment by ume45876139** [comment]
# Working

<details>
<summary>Browser</summary>

https://user-images.githubusercontent.com/39412730/171590127-5072c36f-eb46-49d7-a7a8-dfd828793dde.mp4

</details>

<details>
<summary>iPad</summary>

https://user-images.githubusercontent.com/39412730/171780453-9f868e18-1ff7-45ee-bbdb-ea65f33d6958.mp4

</details>

# Comments

<details>
<summary>iPhone</summary>

http://localhost:3000/feature/chat

IMG_8230

IMG_8231


</details>

- [ ] There is deformation at iPhone 12 mini
    - Illustration is overlapping to Text
    - Text position is wrong at bottom part


# Testing data
test device: Chrome, Safari(iPhone)
test time: 0.5h

**Review by ume45876139 — APPROVED** [review]
# Working

<details>
<summary>Browser</summary>

https://user-images.githubusercontent.com/39412730/171590127-5072c36f-eb46-49d7-a7a8-dfd828793dde.mp4

</details>

<details>
<summary>iPad</summary>

https://user-images.githubusercontent.com/39412730/171780453-9f868e18-1ff7-45ee-bbdb-ea65f33d6958.mp4

</details>

<details>
<summary>iPhone</summary>

http://localhost:3000/feature/chat

IMG_8230

IMG_8231


</details>

- No deformation at Browser and iPad

[note]
- This problem will be fixed by Rose https://app.asana.com/0/1202252431396579/1202381121175289/f
    -  There is deformation at iPhone 12 mini
        - Illustration is overlapping to Text
        - Text position is wrong at bottom part

# Testing data
test device: Chrome, Safari, Opera, Firefox
test time: 0.5h
comment: 3
iteration: 3
total test time: 1.5h

**Review by egiegarciano14 — APPROVED** [review]

**Comment by CaneteJoash** [comment]
### Approved #47

**Pull request merged**
