### PR TITLE
[Task] Create a cookie policy pop up

### PR DESCRIPTION
**Pull request by roseaugusto**
## Related Links

- Task Link: https://www.notion.so/Create-a-cookie-policy-pop-up-9e864a0f54644b2396f6506cbf3fff3d
- Route Link: /

## Description

- Put necessary pop up to inform users of the cookie policy - cookies need to be stored for development | security purposes. Just like this below.
image

## Notes

N/A

## Screenshots
image

### CODE REVIEW

**Comment by ume45876139** [comment]
# Working
<details>
<summary>PC</summary>


https://user-images.githubusercontent.com/39412730/166615560-fab942a6-5a16-4ed1-8454-f2e9c06032a5.mp4


</details>

<details>
<summary>Tablet</summary>


https://user-images.githubusercontent.com/39412730/166615595-128657a9-b0bf-43d2-bde6-af428e2a6ae8.mp4

</details>

<details>
<summary>Mobile</summary>


https://user-images.githubusercontent.com/39412730/166615639-b00de3c0-18c9-4b42-b22b-ed6859a5c0ed.MP4


</details>

- Cookie policy is displayed on the top page
- When user push got it button, cookie policy is hidden
- Chat box is always shown

# Comment

<details>
<summary>Other page</summary>


https://user-images.githubusercontent.com/39412730/166632555-406af5c4-fc45-4348-9a48-fad0358ac6ab.mp4






</details>

- [ ] When user goes to other pages, cookie policy is not displayed

# Testing data
test device: Chrome, Safari
test time: 0.75h
comment: 0
iteration: 0
total test time: 0.75h

**Comment by roseaugusto** [comment]
Never mind this comment, can't delete this though. 🙇‍♀️

**Review by egiegarciano14 — APPROVED** [review]
### Approved PR :+1: 
image

**Review by charlotteds — APPROVED** [review]

**Review by ume45876139 — APPROVED** [review]
# Working
<details>
<summary>PC</summary>


https://user-images.githubusercontent.com/39412730/166637107-a90a01de-6005-4a45-b309-c94ce631202b.mov



</details>

<details>
<summary>Tablet</summary>


https://user-images.githubusercontent.com/39412730/166637136-ef44f56f-4231-4c90-8b95-7619d9bb07ae.mp4


</details>

<details>
<summary>Mobile</summary>


https://user-images.githubusercontent.com/39412730/166637239-a74ee46e-c278-4747-a12c-99e743290519.MP4


</details>

- Cookie policy is displayed on the top page
- When user push got it button, cookie policy is hidden
- Chat box is always shown
- When user goes to other pages, cookie policy is not displayed

# Testing data
test device: Chrome, Safari
test time: 0.25h
comment: 1
iteration: 1
total test time: 1h

**Pull request merged**
