### PR TITLE
[Bugfix] Fix side margins on mobile

### PR DESCRIPTION
**Pull request by roseaugusto**
## Related Links

- Task Link: https://www.notion.so/Fix-side-margins-on-mobile-361ccc8dcca7479e9fb97f2be84deb0d
- Route Link: /

## Description

- Add necessary margins for the following sections/items:
    - Testimonial cards
    - Bottom banner text
image

## Notes

N/A

## Screenshots

N/A

### CODE REVIEW

**Comment by ume45876139** [comment]
# Comment

## Chrome
<details>
<summary>Screenshot</summary>

スクリーンショット 2022-05-05 18 49 14

</details>

- [ ] There is extra space in footer banner


# Testing data
test device: Chrome
test time: 0.25h

**Comment by ume45876139** [comment]
# Comment

<details>
<summary>iPhone</summary>

IMG_50B214081BE9-1

</details>

- [ ] Download buttons are not same line. They are wrapped.


# Testing data
test device: Chrome, Safari
test time: 0.5h

**Comment by ume45876139** [comment]
# Comment

<details>
<summary>iPhone</summary>

IMG_74F684FCBC9D-1

</details>

- [ ]  Text is not aligned center "Your best friend is waiting for you"


# Testing data
test device: Chrome, Safari
test time: 0.25h

**Review by ume45876139 — APPROVED** [review]
# Working
## Chrome
<details>
<summary>PC</summary>

スクリーンショット 2022-05-06 19 26 46

</details>

<details>
<summary>Tablet</summary>

https://user-images.githubusercontent.com/39412730/167115330-fa68a2d2-8d09-49f0-8192-1b39923bd46c.mp4


</details>

<details>
<summary>Mobile</summary>


https://user-images.githubusercontent.com/39412730/167115432-d53e453c-1754-4196-8326-b323148d07f8.MP4

</details>

- There is no deformation
- Testimonial section space is proper
- Text design is correct
- There is no extra space


# Testing data
test device: Chrome, Safari (Mac)
test time: 0.25h
comment: 3
iteration: 3
total test time: 1h

**Review by charlotteds — APPROVED** [review]

**Pull request merged**
